@Api_HostAddress = http://localhost:5000/api/Games
@id = e09843dd-7dd3-4de2-9152-3a4bb994e971

### GET all games
GET {{Api_HostAddress}}
Accept: application/json

### GET {id}
GET {{Api_HostAddress}}/{{id}}
Accept: application/json

### POST
POST {{Api_HostAddress}}
Content-Type: application/json

{
  "name": "Dark SoulsDark"
}

### PUT
PUT {{Api_HostAddress}}/{{id}}
Content-Type: application/json

{
  "id": "{{id}}",
  "name": "Dark Souls Remastered"
}

### DELETE
DELETE {{Api_HostAddress}}/{{id}}
