@Api_HostAddress = http://localhost:5000/api/Games
@id = 8312ec8c-c9db-4162-9b35-985615965c8f

### GET all games
GET {{Api_HostAddress}}
Accept: application/json

### GET {id}
GET {{Api_HostAddress}}/{{id}}
Accept: application/json

### POST
POST {{Api_HostAddress}}
Content-Type: application/json

{
  "name": "Dark SoulsDark"
}

### PUT
PUT {{Api_HostAddress}}/{{id}}
Content-Type: application/json

{
  "id": "{{id}}",
  "name": "Dark Souls Remastered"
}

### DELETE
DELETE {{Api_HostAddress}}/{{id}}
